openapi: 3.0.3
info:
  title: quarkus-openapi
  description: |-
    Quarkus test openapi
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-kl9ng.kl9ng.sandbox2997.opentlc.com/rest/quarkus-openapi/0.0.1"
paths: {}
